module.exports = {
  PORT: process.env.PORT || 5000,
  BOT_TOKEN: process.env.BOT_TOKEN,
  OPENAI_KEY: process.env.OPENAI_API_KEY,
  GNEWS_KEY: process.env.GNEWS_API_KEY,
  GROQ_KEY: process.env.GROQ_API_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  ENCRYPTION_SECRET: process.env.ENCRYPTION_SECRET,
};
